{{- if .Values.component.MCPServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-servicequalmcp
spec:
  ports:
  - {name: http-mcp, port: {{.Values.mcp.port}}, targetPort: mcp-http}
  selector: {impl: {{.Release.Name}}-servicequalmcp}
  type: NodePort
{{- end }}
