apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  componentMetadata:
    id: {{.Values.component.id}}
    name: {{.Values.component.name}}
    functionalBlock: {{.Values.component.functionalBlock}}
    publicationDate: {{.Values.component.publicationDate}}
    status: specified
    version: {{.Values.component.version}}
    description: "Service Catalog Management ODA-Component from Open-API reference implementation."
    maintainers:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com
    owners:
    - name: Lester Thomas
      email: lester.thomas@vodafone.com
  coreFunction:
    exposedAPIs:
    - name: servicecatalogmanagement
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF633_ServiceCatalog/main/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json"
      implementation: {{.Release.Name}}-svcatapi
      apiType: openapi
      id: TMF633
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceCatalogManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceCatalogManagement/v4/docs
      port: 8080
    - name: servicequalitymanagement
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF657_ServiceQualityManagement/main/TMF657_Service_Quality_Management_Management_API_v4.0.0_swagger.json"
      implementation: {{.Release.Name}}-svcqualapi
      apiType: openapi
      id: TMF657
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceQualityManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/serviceQualityManagement/v4/docs
      port: 8080
    {{- if .Values.component.MCPServer.enabled }}
    - name: servicecatalogmcp
      implementation: {{.Release.Name}}-svcatmcp
      apiType: mcp
      path: /{{.Release.Name}}-{{.Values.component.name}}/mcp
      port: 8080
    {{- end }}
    {{- if .Values.processflow.enabled }}
    - name: processflowmanagement
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/main/TMF701-ProcessFlow-v4.0.0.swagger.json"
      implementation: {{.Release.Name}}-procflowapi
      apiType: openapi
      id: TMF701
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/processFlowManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/processFlowManagement/v4/docs
      port: 8080
    {{- end }}
    dependentAPIs:
    {{- if .Values.component.dependentAPIs.enabled }}
    - name: downstreamservicecatalog
      apiType: openapi
      id: TMF633
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF633_ServiceCatalog/main/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json"
    {{- else }}
      []
    {{- end }}
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction:
    exposedAPIs:
    - name: metrics
      apiType: prometheus
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      implementation: {{.Release.Name}}-{{.Values.component.name}}-sm
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  securityFunction:
    canvasSystemRole: {{ .Values.security.canvasSystemRole }}
    exposedAPIs:
    {{- if .Values.permissionspec.enabled }}
    - name: userrolesandpermissions
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolePermissions/master/TMF672-UserRolePermissions-v5.0.0.swagger.json"
      implementation: {{.Release.Name}}-permissionspecapi
      apiType: openapi
      id: TMF672
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      path: /{{.Release.Name}}-{{.Values.component.name}}/rolesAndPermissionsManagement/v5
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/rolesAndPermissionsManagement/v5/docs
      port: 8080
    {{- else }}
    - name: partyrole
      specification:
      - url: "https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json"
      implementation: {{.Release.Name}}-partyroleapi
      apiType: openapi
      id: TMF669
      gatewayConfiguration:
        apiKeyVerification: {{.Values.component.apipolicy.apiKeyVerification | toYaml | nindent 10}}
        rateLimit: {{.Values.component.apipolicy.rateLimit | toYaml | nindent 10}}
        quota: {{.Values.component.apipolicy.quota | toYaml | nindent 10}}
        OASValidation: {{.Values.component.apipolicy.OASValidation | toYaml | nindent 10}}
        CORS: {{.Values.component.apipolicy.CORS | toYaml | nindent 10}}
        template: "{{.Values.component.apipolicy.template}}"
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      port: 8080
    {{- end }}
