apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-productinventoryapi
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: {{.Release.Name}}-productinventoryapi
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-{{.Values.component.name}}
        impl: {{.Release.Name}}-productinventoryapi
        version: {{.Values.api.versionLabel}}
    spec:
      containers:
      - name: {{.Release.Name}}-productinventoryapi         
        image: {{.Values.api.image}}
        env:
        - name: RELEASE_NAME
          value: {{.Release.Name}}           
        - name: COMPONENT_NAME
          value: {{.Release.Name}}-{{.Values.component.name}}
        - name: MONGODB_HOST
          value: {{.Release.Name}}-mongodb
        - name: MONGODB_PORT
          value: "{{.Values.mongodb.port}}"
        - name: MONGODB_DATABASE
          value: {{.Values.mongodb.database}}
        - name: OTL_EXPORTER_CONSOLE_ENABLED
          value: "{{.Values.api.otlp.console.enabled}}"
        - name: OTL_EXPORTER_TRACE_PROTO_ENABLED
          value: "{{.Values.api.otlp.protobuffCollector.enabled}}"
        - name: OTL_EXPORTER_TRACE_PROTO_COLLECTOR_URL
          value: {{.Values.api.otlp.protobuffCollector.url}}
        - name: NODE_ENV
          value: production
        - name: CANVAS_INFO_HOST_PORT
          value: "{{.Values.canvasinfo.host}}" 
        - name: CANVAS_INFO_BASEPATH
          value: "{{.Values.canvasinfo.basepath}}" 
        imagePullPolicy: Always  
        ports:
        - name: {{.Release.Name}}-prodinvapi
          containerPort: 8080
        startupProbe:
          httpGet:
            path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/productInventory/v4/product
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30