apiVersion: v2
name: serviceinventory
description: A reference example TMFC008-ServiceInventory ODA Component

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0
# version: 1.0.0 - Initial TMFC008-ServiceInventory ODA Component implementation
