# Default values for serviceinventory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

component:
  id: TMFC008
  name: serviceinventory
  functionalBlock: Production
  publicationDate: 2024-11-12T00:00:00.000Z
  version: "1.0.0"
  storageClassName: default
  apipolicy:
    apiKeyVerification:
      enabled: false
      location: "header"
    rateLimit:
      enabled: false
      identifier: "IP"
      limit: "6"
      interval: "pm"
    quota:
      identifier: ""
      limit: ""
    OASValidation:
      requestEnabled: false
      responseEnabled: false
      allowUnspecifiedHeaders: false
      allowUnspecifiedQueryParams: false
      allowUnspecifiedCookies: false
    CORS:
      enabled: false
      allowCredentials: false
      allowOrigins: "https://allowed-origin.com, https://allowed-origin2.com"    
      handlePreflightRequests:
        enabled: false
        allowHeaders: "Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers"
        allowMethods: "GET, POST"
        maxAge: 36000
    template: ""
  dependentAPIs:
    enabled: false
    rejectUnauthorizedCertificates: false
    dependencyName: downstreamservicecatalog
security:
  canvasSystemRole: canvasRole
mongodb:
  port: 27017
  database: tmf
api:
  image: lesterthomas/serviceinventoryapi:0.3
  versionLabel: serviceinventoryapi-0.1
  otlp:
    console:
      enabled: false
    protobuffCollector:
      enabled: true
      url: http://observability-opentelemetry-collector.monitoring.svc.cluster.local:4318/v1/traces
metrics:
  image: lesterthomas/serviceinventorymetrics:0.1
partyrole:
  image: lesterthomas/partyroleapi:1.1
  versionLabel: partyroleapi-1.1
permissionspec:
  image: lesterthomas/permissionspecapi:0.20
  versionLabel: permissionspecapi-0.20
  # Set to true to use permissionspec API (TMF672) instead of partyrole API (TMF669)
  enabled: true
canvasinfo:
  host: info.canvas.svc.cluster.local
  basepath: /
