# Default values for productinventory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

component:
  # Specifies whether a service account should be created
  id: TMFC005
  name: productinventory
  functionalBlock: CoreCommerce
  publicationDate: 2023-08-22T00:00:00.000Z
  version: "1.0.1"
  storageClassName: default
  apipolicy:
    apiKeyVerification:
      enabled: false
      location: "header"
    rateLimit:
      enabled: false
      identifier: "IP"
      limit: "6"
      interval: "pm"
    quota:
      identifier: ""
      limit: ""
    OASValidation:
      requestEnabled: false
      responseEnabled: false
      allowUnspecifiedHeaders: false
      allowUnspecifiedQueryParams: false
      allowUnspecifiedCookies: false
    CORS:
      enabled: false
      allowCredentials: false
      allowOrigins: "https://allowed-origin.com, https://allowed-origin2.com"
      handlePreflightRequests:
        enabled: false
        allowHeaders: "Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers"
        allowMethods: "GET, POST"
        maxAge: 36000
    template: ""
security:
  controllerRole: Admin
service:
  type: ClusterIP
  port: 80
mongodb:
  port: 27017
  database: tmf
partyrole:
  image: lesterthomas/partyroleapi:1.0
  versionlabel: partyroleapi-1.0
api:
  image: dominico/productinventoryapi:latest
  versionlabel: productinventoryapi-0.2
